# Generated by Django 5.0.2 on 2024-04-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsedMarketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
