# Generated by Django 5.0.2 on 2024-04-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsedMarketplace', '0003_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
