# Generated by Django 5.0.2 on 2024-04-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsedMarketplace', '0005_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('logged_in', models.BooleanField(default=False)),
            ],
        ),
    ]
